### PR TITLE
Fix to adapter.

### LINKED ISSUE #79: SAP_Toolkit : adapter push throws an error
#### Description:

Pushing a SAPReport Object to a file causes an error reagrding fragments

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #79

Error in the push for the adapter has been fixed. This should now run.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
Thanks @BHoMBot check serialisation
@BHoMBot check core

**Comment by EKAdebo** [comment]
@BHoMBot check serialisation
@BHoMBot check core

**Review by FraserGreenroyd — APPROVED** [review]
Looks ok from code review

**Pull request merged**
