### PR TITLE
Fix XML definitions and execute outputs

### LINKED ISSUE #54: Fix XML definitions and deserialization
#### Description:

Issues with the SAP.XML definitions when trying to deserialize them. Needs to be fixed to properly get a XML objects as ouput in the execute.

- check definitions for duplicates
- general debugging and testing to find the problem

### PR DESCRIPTION
**Pull request by emilsvedjer**
### Issues addressed by this PR

Closes #54 

XML definitions updated and are now serializable. Execute method updated to enable XML output.
All endpoints in execute are now working.
ObjectFromXML.cs is now working due to the changes in the XML definitions. 

### Test files

[here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP_Toolkit/%2355.gh?csf=1&web=1&e=ceCSJu)

### CODE REVIEW

**Comment by emilsvedjer** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 6505351954

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 6505351954

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by rboulton-BH — APPROVED** [review]
I've tested this using the script provided. The push of a full dwelling to XML is now functional and all of the end points now work appropriately using the example dwelling files. I tried pushing a custom dwelling XML to the endpoint but it failed, probably because not all of the required inputs were provided. So I think the code in this PR works fundamentally but we're going to need to build in some checks and improve exception handling.

**Pull request merged**
