### PR TITLE
Fix for objects not implementing IObject.

### LINKED ISSUE #77: SAP_Toolkit: Objects not implementing IObject
#### Broken rules:

The following objects from AllTypeList() with a namespace starting with BH.oM or BH.Revit.oM does not implement the IObject interface (directly or via another interface):

Failing interface types:
BH.oM.Environment.SAP.IResultObject

Failing class types:
BH.oM.Environment.SAP.Modify

#### Suggestions to restore compliance:

add IObject interface either to BaseInterface covering more classes, or to class itself.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #77 

 Changing namespace in GroupByDwelling file, and adding IObject interface to IResultObject file.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Nice quick fix, thanks @EKAdebo . Code reviewed and makes sense for what was needed.

**Pull request merged**
