### PR TITLE
Process results into Excel files

### LINKED ISSUE #152: Handle results
As part of the refactor handle the results in a nice way

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #152

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by rboulton-BH — APPROVED** [review]
Changes respond to requested features. Initial tests looking good. Approve

**Pull request merged**
