### PR TITLE
Create objects for excel data.

### LINKED ISSUE #122: Create excel objects for pull
#### Description:

Create objects to be used to hold data from the pull of the excel spreadsheet created to assist this workflow.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #122 

Several objects have been created on top of two existing ones to be used when pulling the SAP data from excel. They have also been moved to a new folder in the oM.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Works in line with workshop, thanks @EKAdebo

**Pull request merged**
