### PR TITLE
Fix copyright issues

### LINKED ISSUE #132: Fix copyright compliance
Per https://github.com/BHoM/SAP_Toolkit/pull/130/checks?check_run_id=16896135495

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #132

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisatoin

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check compliance

**Review by albinber — APPROVED** [review]
All seems good

**Pull request merged**
