### PR TITLE
Fix bugs in XML generation for Argyle

### LINKED ISSUE #146: Bugs in XML generation
Following project use case with @rboulton-BH and Sam.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #146

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check serialisation
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 17098649260

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 17098654178

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation

**Review by rboulton-BH — APPROVED** [review]
Code changes respond to bugs and UX issues as discussed. Testing suggest the bugs are fixed so happy to approve

**Pull request merged**
