### PR TITLE
Rewrite python components

### LINKED ISSUE #123: Rewrite python components in script to c#
#### Description:

There are several python components within the grasshopper script that should be included as c# methods in the toolkit.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #123

Two python components in the script have been rewritten. They both rename parts of the script, one renames the walls and roofs to be in line with the schema, and the other renames the opening types to be in line with the argyle schema.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Good work per workshop @EKAdebo 😄

**Pull request merged**
