### PR TITLE
SAP_Toolkit: Changing floor U Value type from string to double

### PR DESCRIPTION
**Pull request by EKAdebo**
Changing floor U Value type from string to double
As discussed with @rboulton-BH

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by kprusicka — APPROVED** [review]
Looks reasonable

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
If @kprusicka likes it, it can't be wrong 🙄  🤣 
Have reviewed the code, changes look good. Failure in core is caused by a missing dependency for BHoM_Adapter for the check - will resolve in a separate PR.

**Pull request merged**
