### PR TITLE
Replacing IsNullOrEmpty

### LINKED ISSUE #97: Fix null check error
#### Description:

Within the parametrics methods, the method IsNullOrEmpty is called, this produces an error in the grasshopper components that reads "Cannot evaluate ________ because the List failed a null check".

Switch out this method for equivalent so that this error is not produced.

### PR DESCRIPTION
**Pull request by EKAdebo**
Closes #97 

This replaces the IsNullOrEmpty method in OpeningType.cs with ((item != null) && item.Any())

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 14477708140

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Change makes sense and looks good to me 👍

**Pull request merged**
