### PR TITLE
Removal of methods involving or references to Stroma Json file.

### LINKED ISSUE #119: Delete stroma related files
#### Description:

Delete the files related to stroma jsons and also the convert methods for them.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #119 

This deletes any files that reference to the stroma JSON schema or has methods that involves objects based on the stroma schema. It also includes removing references in several other files that had "using BH.oM.Environment.SAP.Stroma10" listed in them.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — DISMISSED** [review]
All looks good - deleting stuff is fun @EKAdebo ! 😄

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by albinber — APPROVED** [review]
Code looks good, I approve.

**Pull request merged**
