### PR TITLE
Updating dependencies file.

### LINKED ISSUE #75: Update dependencies file
To add `BHoM/BHoM_Adapter`.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #75 

The dependencies file has been updated to include BHoM/BHoM_Adapter.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: core

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
Added correct change and core now passes. Thanks @EKAdebo

**Review by kprusicka — APPROVED** [review]
Amazing stuff thank you!!!

**Pull request merged**
