### PR TITLE
Update of parametric study components

### LINKED ISSUE #109: Update of parametric study components.
#### Description:

Update to include comments describing code, correct descriptions of methods and descriptors of inputs and outputs. Some of the methods should also be simplified.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #109

Updates parametric study components with comments and hopefully so they can be read more easily.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Good work @EKAdebo - happy to deploy for the weekend 😉

**Pull request merged**
