### PR TITLE
Updated ClosedXML version to 0.102.2

### LINKED ISSUE #175: Update CloseXML version to 0.102.2
#### Description:

At some point the version of closed xml used by Excel toolkit and this one have diverged, causing pushing of results to excel files to stop working. The currently open PR (#173) would do this, however it is linked to the Excel toolkit PR for updating the target framework to `netstandard2.0`.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #175 

As in the issue, same change as in #173, but not linked to an excel toolkit PR

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@Tom-Kingstone, won't we end up with 2 versions of ClosedXML in the BHoM\Assemblies folder? If not, then it should be perfectly fine to decouple from Excel_Toolkit 👍

**Review by JohannaOlin1 — APPROVED** [review]
Tested on the SAP script where the issue with the ClosedXML assemblies occurred, which now works

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance

**Comment by Tom-Kingstone** [comment]
> @Tom-Kingstone, won't we end up with 2 versions of ClosedXML in the BHoM\Assemblies folder? If not, then it should be perfectly fine to decouple from Excel_Toolkit 👍

@pawelbaran 
I'll give it a check using today's alpha installer, and the installer the bot made from this PR, but I think that the problem before is that two different versions of ClosedXML are being targeted currently, and this just aligns the two together. There can't be two `ClosedXML.dll` files in the assemblies folder, though I don't know how one version is decided over another (maybe compile order?)

To be clear, the version that Excel_Toolkit targets is 0.102.2

**Comment by Tom-Kingstone** [comment]
I checked with yesterday's alpha, and that installs ClosedXML version 0.102.2
image
And the installer for this branch also installs the same version, so it should be ok to merge

**Comment by pawelbaran** [comment]
All clear @Tom-Kingstone, actually my comment may have been irrelevant from the very beginning - the fact the original PR was linked with the Excel_Toolkit PR raised a flag in my head as I have spent lots of time trying to fix it the other day. However, as you notice, this PR only aligns with what we already have in BHoM, so naturally nothing against it 👍 Thank you and apologies for confusion, if any 🙈

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
