### PR TITLE
Demo link with Argyle

### LINKED ISSUE #16: SAP_Toolkit: Prototype Adapter For Argyle SAP engine
#### Description:

Following the workshop this morning with Argyle, we should develop a prototype method of pushing a sample SAP XML file up to the Argyle SAP engine on the Amazon Lambda service and recieve the XML back with the calculated results.

### LINKED ISSUE #18: SAP_Toolkit: SAP object create methods from 2D PDF & spec table
#### Description:

Need to establish a method of creating SAP objects from our existing 2D PDF markup workflow. The markups will provide the geometry data, but the dwelling info, building fabric and system spec will need to be applied separately. I suggest this is pulled from an Excel table

### LINKED ISSUE #24: SAP_Toolkit: AddOpenings method
#### Description:

New method to automatically assign SAP Opening objects to SAP Wall objects based on matching a common DwellingName. By default I would recommend assigning all Openings in a dwelling to the largest Wall but we will need to include handling of the case where the total area of the Openings is greater than the area of the largest Wall.

### PR DESCRIPTION
**Pull request by rboulton-BH**
### Issues addressed by this PR

Includes prototype SAP adapter to connect to Argyle engine hosted on AWS Lambda and updated SAP object definitions

Closes #24
Closes #16 
Closes #18 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/Direction/designtechnology/RandDWishlist/00205_Environments%20%26%20MEP/SAP%20workflow/211027%20Dwellings%20from%20Bluebeam.gh?csf=1&web=1&e=gwW4Ij

### CODE REVIEW

**Review by emilsvedjer — APPROVED** [review]
LOTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 4442828967

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 4442828495

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance
@BHoMBot check core

**Review by FraserGreenroyd — APPROVED** [review]

**Pull request merged**
