### PR TITLE
SAP_Toolkit #46 Add template dwelling XML and pushToXML convert method

### LINKED ISSUE #46: SAP_Toolkit: Set up template dwelling XML
#### Description:

To be able to get a prototype workflow up and running asap we need to be able to create valid full dwelling XML files to send to the Argyle engine. These contain many parameters which are currently not covered in the SAP object definitions and are generally not needed within our typical workflows. Instead of defining the SAP objects discretely we've decided to hard-code a template XML dwelling/assessment which we can combine with the custom <SAP2012-Data> property to build up a full and valid XML file.

Properties to be included in template:
```
<?xml version>
<SAP-Report>
  <Schema-Version-Original>
  <SAP-Version>
  <SAP-Data-Version>
  <PCDF-Revision-Number>
  <Calculation-Software-Name>
  <Calculation-Software-Version>
  <Report-Header>
  <Energy-Assessment>
  <Insurance-Details>
  <ExternalDefinitions-Revision-Number>
```

### PR DESCRIPTION
**Pull request by rboulton-BH**
### Issues addressed by this PR

Closes #46 

### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SAP_Toolkit/%2346-templateDwelling-pushToXML.gh?csf=1&web=1&e=DN26lf

### Additional comments

Doesn't actually work yet, will require audit of SAP2012Data XML definition to ensure correct serialisation

### CODE REVIEW

**Review by emilsvedjer — DISMISSED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 6404099208

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 6404136310

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by FraserGreenroyd — APPROVED** [review]

**Pull request merged**
