### PR TITLE
Methods to query areas

### LINKED ISSUE #92: Querying areas
#### Description:

It would be useful to have methods to query the total floor area, wall area, and window area of a dwelling.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #92 

Creation of three methods to query wall area, total floor area, and wall area from a SAP report object. Changes were also made to how data such as area/width/height were stored within an xml object (changed from string to double) and other methods where changed to reflect this.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Code looks good, good work @EKAdebo

**Pull request merged**
