### PR TITLE
Fix for parametric study components.

### LINKED ISSUE #90: Parametrics not working
#### Description:

The ParametricsUvalueGvalue method doesn't seem to be making any changes to the u value or the g value/solar factor of the specified opening type.

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #90 

There was an issue with a for loop in the opening types method.  this was fixed and now the components run as expected. Other changes were made due to them also causing minor errors when running the parametric studies.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by EKAdebo** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — DISMISSED** [review]
All looks good, great work!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Reapproving following rebase.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core

**Pull request merged**
