### PR TITLE
Refactor to improve UX and use within Visual Programming

### LINKED ISSUE #129: Refactor to improve UX
Following on from the workshop with @EKAdebo last week, the following should be completed to improve UX:

 - Remake SAP_Adapter to take in more inputs/arguments/configuration options to pull SAP Reports, and join up information coming in from Excel (currently this is a large amount of components on the Grasshopper canvas, so this will be a simplification exercise).
 - Rename the SAP Connection for Argyle from SAP_Adapter to Argyle_Adapter to make things easier for users (specifying the SAP engine effectively via the adapter).

FYI @rboulton-BH @albinber @EKAdebo

### LINKED ISSUE #131: Fix project compliance
Per https://github.com/BHoM/SAP_Toolkit/pull/130/checks?check_run_id=16895896131

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #129 
Fixes #131

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, serialisation, copyright-compliance, project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: project-compliance, code-compliance, documentation-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by albinber — APPROVED** [review]
Worked through with @FraserGreenroyd during workshop today, everything works as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: copyright-compliance

**Pull request merged**
