### PR TITLE
Adding a comment to Execute.cs

### LINKED ISSUE #84: Add code comment to Execute.cs
Line 82 of Execute.cs - can we add a code comment which says something along the lines of:

`//All outputs from the engine are text based, regardless of whether they are XML/JSON/Text - rather than let try/catches determine file type, just output straight to a file and return the file path for the user to pull back into their canvas if desired.`

This is to prevent forgetting why we made that change and having to read the past code from https://github.com/BHoM/SAP_Toolkit/commit/f24b4bfd05b9ee6c9f6bf2bc62c7cf635a77a037#diff-10ce9cc099f88360ff1e966761469eb55a423fe79ead2b2287c4add5590274e7 to work it out, as @rboulton-BH and I just had to...

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #84 

A comment "All outputs from the engine are text based, this outputs straight to the file defined file path set by the user. " has been added to the file Execute.cs on line 82 as specified in the linked issue (#84). Some updates have also been made to null values.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check compliance

**Comment by EKAdebo** [comment]
@BHoMBot check core

**Comment by EKAdebo** [comment]
@BHoMBot check serialisation

**Comment by EKAdebo** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Happy with the comment addition, and discussed other changes offline with @EKAdebo to deal with in tomorrows workshop.

**Pull request merged**
