### PR TITLE
Pull/Push issues fix

### LINKED ISSUE #70: SAP_Toolkit: Fix issues in SAP_Toolkit
#### Description:

Update code in SAP-TK so that the push works (i.e fixing incorrect names and conventions etc).

### PR DESCRIPTION
**Pull request by EKAdebo**
### Issues addressed by this PR

Closes #70

Updates to pull/push methods and objects to create valid XMLs.

### CODE REVIEW

**Comment by EKAdebo** [comment]
@BHoMBot check copyright-compliance

**Comment by EKAdebo** [comment]
@BHoMBot check project-compliance

**Review by FraserGreenroyd — DISMISSED** [review]
LGTM - everything is in line with recent review/test with @rboulton-BH yesterday - merging to deploy and have final review against all code.

**Comment by EKAdebo** [comment]
@BHoMBot fix project file ref. 13034281052

**Review by FraserGreenroyd — APPROVED** [review]
Latest commit for compliance only by the bot

**Comment by EKAdebo** [comment]
Hi!
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Pull request merged**
